name: Release

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Prepare release files
        run: |
          mkdir -p release/applications release/system/bin
          cp $GITHUB_WORKSPACE/PB4root.app release/applications
          cp $GITHUB_WORKSPACE/root.sh release/system/bin
          curl https://raw.githubusercontent.com/ezdiy/pbjb/v8/su -o release/system/bin/su
      
      - name: Archive release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          directory: 'release/'
      
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release/release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
